/**
 * Templates taken off sale because they do not work and cannot be made to.
 *
 * The rule: a template is withdrawn when one of its nodes carries a parameter
 * set that cannot belong to its node type - 52 nodes typed
 * `n8n-nodes-base.mySql` hold `documentId`, `sheetName` and
 * `operation: "appendOrUpdate"`, which is the Google Sheets parameter set, and
 * no MySQL parameters at all. There is no configuration that fixes that; the
 * node has to be rebuilt. 496 templates are affected.
 *
 * This is a different category from the other corpus defects. An unbound
 * resource locator or a missing `lib:` sub-workflow leaves the buyer with work
 * to do, and the setup checklist now tells them so before they pay. A node with
 * the wrong parameters leaves them with a file that was never going to run.
 * Disclosing that and offering a refund is still selling it.
 *
 * The set is generated by scripts/build-withdrawn.mjs, which runs the same
 * `buildSetupChecklist` the product page renders from - the withdrawal list and
 * the on-page defect banner cannot disagree about which templates are broken.
 * It is a generated artifact rather than a live scan because the predicate has
 * to read `parameters` from every product file.
 *
 * Withdrawal removes a template from the sellable catalog, which is what
 * `getIndex`/`getCatalog` return. That makes every listing, search, filter,
 * collection, bundle, price and sitemap correct without each having to know
 * this module exists - the safe default, because anything overlooked stays
 * correct. Two places deliberately opt back in to the full set:
 *
 *   - the product page, which serves 200 with a notice rather than a 404, so
 *     an indexed URL does not rot and a curious buyer gets an explanation
 *   - the download authoriser, so that if anyone ever bought one of these
 *     before withdrawal, their entitlement still resolves. Withdrawal blocks
 *     new purchases; it never revokes one already made.
 */
// Relative rather than the "@/" alias: this module is pulled in by the catalog
// loader, which the data-checking scripts compile and run outside Next, and the
// emitted CommonJS keeps a path alias verbatim. A JSON import (rather than fs)
// keeps it usable from client components, same reason site.ts does it.
import withdrawnData from "../data/withdrawn.json";

type WithdrawnRecord = {
  reason: string;
  count: number;
  items: Array<{ id: string; route: string; nodes: string[] }>;
};

const data = withdrawnData as WithdrawnRecord;

let idSet: Set<string> | undefined;
let routeSet: Set<string> | undefined;

export const WITHDRAWN_COUNT = data.items.length;

/** Why every template in the set is withdrawn - one rule, so one sentence. */
export const WITHDRAWN_REASON = data.reason;

export function withdrawnIds(): Set<string> {
  idSet ??= new Set(data.items.map((w) => w.id));
  return idSet;
}

export function withdrawnRoutes(): Set<string> {
  routeSet ??= new Set(data.items.map((w) => w.route));
  return routeSet;
}

export function isWithdrawnId(id: string): boolean {
  return withdrawnIds().has(id);
}

export function isWithdrawnRoute(route: string): boolean {
  return withdrawnRoutes().has(route);
}

/** The nodes that caused a withdrawal, for the notice on the product page. */
export function withdrawnNodes(id: string): string[] {
  return data.items.find((w) => w.id === id)?.nodes ?? [];
}
